markdown:    kramdown
highlighter: rouge
permalink:   pretty

port:        4000
url:         lucasgruwez.github.io
baseurl:     /lunar-icons

version:     v2.1.0
gzip:        5kb
icons:       150+

cdn:         https://unpkg.com/lunar-icons@2.0.1
repo:        https://github.com/lucasgruwez/lunar-icons
npm:         https://npmjs.org/packages/lunar-icons
author:      https://github.com/lucasgruwez






